package com.example.springboot.model;

import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.id
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.name
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.price
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.cost
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Double cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.salesCount
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Integer salescount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.realProductSalesCount
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Integer realproductsalescount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.visitCount
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Integer visitcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.attentionCount
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Integer attentioncount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.isSales
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Boolean issales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.shopId
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Integer shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.shopName
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private String shopname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.deliveryAddress
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private String deliveryaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.brandId
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Integer brandid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.brand
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.isCustom
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Boolean iscustom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.isNotMianYi
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Boolean isnotmianyi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.mark
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Byte mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.model
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.categoryId1
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Integer categoryid1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.categoryName1
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private String categoryname1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.categoryId2
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Integer categoryid2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.categoryName2
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private String categoryname2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.categoryId3
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Integer categoryid3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.categoryName3
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private String categoryname3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.realProductId
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Integer realproductid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.code
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.sortIndex
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Double sortindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.filenameDefault
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private String filenamedefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.orderMinCount
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Integer ordermincount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.count
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.subName
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private String subname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.promotionTypeSum
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Integer promotiontypesum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.channelTypeSum
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Integer channeltypesum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.hmd_createTime
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Date hmdCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.hmd_updateTime
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Date hmdUpdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.del_flag
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private Byte delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.id
     *
     * @return the value of hmd_product_product.id
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.id
     *
     * @param id the value for hmd_product_product.id
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.name
     *
     * @return the value of hmd_product_product.name
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.name
     *
     * @param name the value for hmd_product_product.name
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.price
     *
     * @return the value of hmd_product_product.price
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.price
     *
     * @param price the value for hmd_product_product.price
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.cost
     *
     * @return the value of hmd_product_product.cost
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Double getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.cost
     *
     * @param cost the value for hmd_product_product.cost
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setCost(Double cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.salesCount
     *
     * @return the value of hmd_product_product.salesCount
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Integer getSalescount() {
        return salescount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.salesCount
     *
     * @param salescount the value for hmd_product_product.salesCount
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setSalescount(Integer salescount) {
        this.salescount = salescount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.realProductSalesCount
     *
     * @return the value of hmd_product_product.realProductSalesCount
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Integer getRealproductsalescount() {
        return realproductsalescount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.realProductSalesCount
     *
     * @param realproductsalescount the value for hmd_product_product.realProductSalesCount
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setRealproductsalescount(Integer realproductsalescount) {
        this.realproductsalescount = realproductsalescount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.visitCount
     *
     * @return the value of hmd_product_product.visitCount
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Integer getVisitcount() {
        return visitcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.visitCount
     *
     * @param visitcount the value for hmd_product_product.visitCount
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setVisitcount(Integer visitcount) {
        this.visitcount = visitcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.attentionCount
     *
     * @return the value of hmd_product_product.attentionCount
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Integer getAttentioncount() {
        return attentioncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.attentionCount
     *
     * @param attentioncount the value for hmd_product_product.attentionCount
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setAttentioncount(Integer attentioncount) {
        this.attentioncount = attentioncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.isSales
     *
     * @return the value of hmd_product_product.isSales
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Boolean getIssales() {
        return issales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.isSales
     *
     * @param issales the value for hmd_product_product.isSales
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setIssales(Boolean issales) {
        this.issales = issales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.shopId
     *
     * @return the value of hmd_product_product.shopId
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.shopId
     *
     * @param shopid the value for hmd_product_product.shopId
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.shopName
     *
     * @return the value of hmd_product_product.shopName
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public String getShopname() {
        return shopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.shopName
     *
     * @param shopname the value for hmd_product_product.shopName
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setShopname(String shopname) {
        this.shopname = shopname == null ? null : shopname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.deliveryAddress
     *
     * @return the value of hmd_product_product.deliveryAddress
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public String getDeliveryaddress() {
        return deliveryaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.deliveryAddress
     *
     * @param deliveryaddress the value for hmd_product_product.deliveryAddress
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setDeliveryaddress(String deliveryaddress) {
        this.deliveryaddress = deliveryaddress == null ? null : deliveryaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.brandId
     *
     * @return the value of hmd_product_product.brandId
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Integer getBrandid() {
        return brandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.brandId
     *
     * @param brandid the value for hmd_product_product.brandId
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setBrandid(Integer brandid) {
        this.brandid = brandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.brand
     *
     * @return the value of hmd_product_product.brand
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.brand
     *
     * @param brand the value for hmd_product_product.brand
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.isCustom
     *
     * @return the value of hmd_product_product.isCustom
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Boolean getIscustom() {
        return iscustom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.isCustom
     *
     * @param iscustom the value for hmd_product_product.isCustom
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setIscustom(Boolean iscustom) {
        this.iscustom = iscustom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.isNotMianYi
     *
     * @return the value of hmd_product_product.isNotMianYi
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Boolean getIsnotmianyi() {
        return isnotmianyi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.isNotMianYi
     *
     * @param isnotmianyi the value for hmd_product_product.isNotMianYi
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setIsnotmianyi(Boolean isnotmianyi) {
        this.isnotmianyi = isnotmianyi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.mark
     *
     * @return the value of hmd_product_product.mark
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Byte getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.mark
     *
     * @param mark the value for hmd_product_product.mark
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setMark(Byte mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.model
     *
     * @return the value of hmd_product_product.model
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.model
     *
     * @param model the value for hmd_product_product.model
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.categoryId1
     *
     * @return the value of hmd_product_product.categoryId1
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Integer getCategoryid1() {
        return categoryid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.categoryId1
     *
     * @param categoryid1 the value for hmd_product_product.categoryId1
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setCategoryid1(Integer categoryid1) {
        this.categoryid1 = categoryid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.categoryName1
     *
     * @return the value of hmd_product_product.categoryName1
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public String getCategoryname1() {
        return categoryname1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.categoryName1
     *
     * @param categoryname1 the value for hmd_product_product.categoryName1
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setCategoryname1(String categoryname1) {
        this.categoryname1 = categoryname1 == null ? null : categoryname1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.categoryId2
     *
     * @return the value of hmd_product_product.categoryId2
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Integer getCategoryid2() {
        return categoryid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.categoryId2
     *
     * @param categoryid2 the value for hmd_product_product.categoryId2
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setCategoryid2(Integer categoryid2) {
        this.categoryid2 = categoryid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.categoryName2
     *
     * @return the value of hmd_product_product.categoryName2
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public String getCategoryname2() {
        return categoryname2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.categoryName2
     *
     * @param categoryname2 the value for hmd_product_product.categoryName2
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setCategoryname2(String categoryname2) {
        this.categoryname2 = categoryname2 == null ? null : categoryname2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.categoryId3
     *
     * @return the value of hmd_product_product.categoryId3
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Integer getCategoryid3() {
        return categoryid3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.categoryId3
     *
     * @param categoryid3 the value for hmd_product_product.categoryId3
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setCategoryid3(Integer categoryid3) {
        this.categoryid3 = categoryid3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.categoryName3
     *
     * @return the value of hmd_product_product.categoryName3
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public String getCategoryname3() {
        return categoryname3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.categoryName3
     *
     * @param categoryname3 the value for hmd_product_product.categoryName3
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setCategoryname3(String categoryname3) {
        this.categoryname3 = categoryname3 == null ? null : categoryname3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.realProductId
     *
     * @return the value of hmd_product_product.realProductId
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Integer getRealproductid() {
        return realproductid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.realProductId
     *
     * @param realproductid the value for hmd_product_product.realProductId
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setRealproductid(Integer realproductid) {
        this.realproductid = realproductid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.code
     *
     * @return the value of hmd_product_product.code
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.code
     *
     * @param code the value for hmd_product_product.code
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.sortIndex
     *
     * @return the value of hmd_product_product.sortIndex
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Double getSortindex() {
        return sortindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.sortIndex
     *
     * @param sortindex the value for hmd_product_product.sortIndex
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setSortindex(Double sortindex) {
        this.sortindex = sortindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.filenameDefault
     *
     * @return the value of hmd_product_product.filenameDefault
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public String getFilenamedefault() {
        return filenamedefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.filenameDefault
     *
     * @param filenamedefault the value for hmd_product_product.filenameDefault
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setFilenamedefault(String filenamedefault) {
        this.filenamedefault = filenamedefault == null ? null : filenamedefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.orderMinCount
     *
     * @return the value of hmd_product_product.orderMinCount
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Integer getOrdermincount() {
        return ordermincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.orderMinCount
     *
     * @param ordermincount the value for hmd_product_product.orderMinCount
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setOrdermincount(Integer ordermincount) {
        this.ordermincount = ordermincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.count
     *
     * @return the value of hmd_product_product.count
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.count
     *
     * @param count the value for hmd_product_product.count
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.subName
     *
     * @return the value of hmd_product_product.subName
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public String getSubname() {
        return subname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.subName
     *
     * @param subname the value for hmd_product_product.subName
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setSubname(String subname) {
        this.subname = subname == null ? null : subname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.promotionTypeSum
     *
     * @return the value of hmd_product_product.promotionTypeSum
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Integer getPromotiontypesum() {
        return promotiontypesum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.promotionTypeSum
     *
     * @param promotiontypesum the value for hmd_product_product.promotionTypeSum
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setPromotiontypesum(Integer promotiontypesum) {
        this.promotiontypesum = promotiontypesum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.channelTypeSum
     *
     * @return the value of hmd_product_product.channelTypeSum
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Integer getChanneltypesum() {
        return channeltypesum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.channelTypeSum
     *
     * @param channeltypesum the value for hmd_product_product.channelTypeSum
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setChanneltypesum(Integer channeltypesum) {
        this.channeltypesum = channeltypesum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.hmd_createTime
     *
     * @return the value of hmd_product_product.hmd_createTime
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Date getHmdCreatetime() {
        return hmdCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.hmd_createTime
     *
     * @param hmdCreatetime the value for hmd_product_product.hmd_createTime
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setHmdCreatetime(Date hmdCreatetime) {
        this.hmdCreatetime = hmdCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.hmd_updateTime
     *
     * @return the value of hmd_product_product.hmd_updateTime
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Date getHmdUpdatetime() {
        return hmdUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.hmd_updateTime
     *
     * @param hmdUpdatetime the value for hmd_product_product.hmd_updateTime
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setHmdUpdatetime(Date hmdUpdatetime) {
        this.hmdUpdatetime = hmdUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.del_flag
     *
     * @return the value of hmd_product_product.del_flag
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.del_flag
     *
     * @param delFlag the value for hmd_product_product.del_flag
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }
}