package com.example.springboot.model;

public class ProductWithBLOBs extends Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.searchKeywords
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private String searchkeywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.propertys
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private String propertys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.propertyIds
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private String propertyids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.preparetionIntro
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private String preparetionintro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.promotionIDs
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private String promotionids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.promotionTypes
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private String promotiontypes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmd_product_product.channelTypes
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    private String channeltypes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.searchKeywords
     *
     * @return the value of hmd_product_product.searchKeywords
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public String getSearchkeywords() {
        return searchkeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.searchKeywords
     *
     * @param searchkeywords the value for hmd_product_product.searchKeywords
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setSearchkeywords(String searchkeywords) {
        this.searchkeywords = searchkeywords == null ? null : searchkeywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.propertys
     *
     * @return the value of hmd_product_product.propertys
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public String getPropertys() {
        return propertys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.propertys
     *
     * @param propertys the value for hmd_product_product.propertys
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setPropertys(String propertys) {
        this.propertys = propertys == null ? null : propertys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.propertyIds
     *
     * @return the value of hmd_product_product.propertyIds
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public String getPropertyids() {
        return propertyids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.propertyIds
     *
     * @param propertyids the value for hmd_product_product.propertyIds
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setPropertyids(String propertyids) {
        this.propertyids = propertyids == null ? null : propertyids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.preparetionIntro
     *
     * @return the value of hmd_product_product.preparetionIntro
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public String getPreparetionintro() {
        return preparetionintro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.preparetionIntro
     *
     * @param preparetionintro the value for hmd_product_product.preparetionIntro
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setPreparetionintro(String preparetionintro) {
        this.preparetionintro = preparetionintro == null ? null : preparetionintro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.promotionIDs
     *
     * @return the value of hmd_product_product.promotionIDs
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public String getPromotionids() {
        return promotionids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.promotionIDs
     *
     * @param promotionids the value for hmd_product_product.promotionIDs
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setPromotionids(String promotionids) {
        this.promotionids = promotionids == null ? null : promotionids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.promotionTypes
     *
     * @return the value of hmd_product_product.promotionTypes
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public String getPromotiontypes() {
        return promotiontypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.promotionTypes
     *
     * @param promotiontypes the value for hmd_product_product.promotionTypes
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setPromotiontypes(String promotiontypes) {
        this.promotiontypes = promotiontypes == null ? null : promotiontypes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmd_product_product.channelTypes
     *
     * @return the value of hmd_product_product.channelTypes
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public String getChanneltypes() {
        return channeltypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmd_product_product.channelTypes
     *
     * @param channeltypes the value for hmd_product_product.channelTypes
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    public void setChanneltypes(String channeltypes) {
        this.channeltypes = channeltypes == null ? null : channeltypes.trim();
    }
}