package com.example.springboot.mapper;

import com.example.springboot.model.ProductWithBLOBs;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmd_product_product
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    int insert(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmd_product_product
     *
     * @mbg.generated Thu Dec 06 15:48:23 CST 2018
     */
    int insertSelective(ProductWithBLOBs record);
}